### ISSUE TITLE
No documentation on restore procedures

### ISSUE THREAD

**Issue by ethanpil** [noahlh/aws-automated-backup-powershell#11]
Per the title, I dont see any instructions on how one would restore from these backups...

**Comment by TNTGav** [comment]
I think this is beyond the scope of the script documentation. To be honest, if anyone reading this doesn't know how to restore a snapshot in Amazon then you shouldn't be running this script until you do.

**Comment by noahlh** [comment]
Agreed.  But!  If someone wants to write up documentation on this (for the sake of beginners), I'll happily merge.  Closing for now.
