### ISSUE TITLE
Errors on Script

### ISSUE THREAD

**Issue by dms2015** [noahlh/aws-automated-backup-powershell#15]
I am receiving the below errors on the script.  I also loaded the aws sdk (installed) but the original AWSSDK.dll doesn't exist in that folder so I modified it to EC2 for my AWS SDK Path.  Can I change it to this dll?

#AWS SDK Path 
Add-Type -Path "C:\Program Files (x86)\AWS SDK for .NET\bin\Net45\AWSSDK.EC2.dll"

This is the Error I am receiving after I errored out on the above:
Unable to find type [Amazon.AWSClientFactory]: make sure that the assembly 
containing this type is loaded.
At C:\AWS\AWSConfig.ps1:42 char:1
+ $EC2_CLIENT=[Amazon.AWSClientFactory]::CreateAmazonEC2Client($accessKeyID, 
$secr ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~~~
    + CategoryInfo          : InvalidOperation: (Amazon.AWSClientFactory:TypeN 
   ame) [], RuntimeException
    + FullyQualifiedErrorId : TypeNotFound
 
New-Object : Cannot find type 
[Amazon.SimpleEmail.AmazonSimpleEmailServiceConfig]: make sure the assembly 
containing this type is loaded.
At C:\AWS\AWSConfig.ps1:45 char:13
+ $ses_config=New-Object Amazon.SimpleEmail.AmazonSimpleEmailServiceConfig
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidType: (:) [New-Object], PSArgumentExcepti 
   on
    + FullyQualifiedErrorId : TypeNotFound,Microsoft.PowerShell.Commands.NewOb 
   jectCommand
 
Property 'ServiceURL' cannot be found on this object; make sure it exists and 
is settable.
At C:\AWS\AWSConfig.ps1:46 char:1
+ $ses_config.ServiceURL = $sesURL
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : PropertyNotFound
 
Unable to find type [Amazon.AWSClientFactory]: make sure that the assembly 
containing this type is loaded.
At C:\AWS\AWSConfig.ps1:47 char:1
+ $SES_CLIENT=[Amazon.AWSClientFactory]::CreateAmazonSimpleEmailServiceClient($
acc ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~~~
    + CategoryInfo          : InvalidOperation: (Amazon.AWSClientFactory:TypeN 
   ame) [], RuntimeException
    + FullyQualifiedErrorId : TypeNotFound

**Comment by matteobraga** [comment]
I receive this error

27/08/2015 09.15.16 WriteToLog : System.NotSupportedException: Specified method is not supported.
   at System.Management.Automation.ParameterBinderBase.CoerceTypeAsNeeded(CommandParameterInternal argument, String parameterName, Type toType, ParameterCollectionTypeInformation collectionTypeInfo, Object currentValue)

**Comment by amanakash** [comment]
@dms2015 you can find some help in this closed issue.

https://github.com/noahlh/aws-automated-backup-powershell/issues/14#issuecomment-131584777

**Comment by necarlson** [comment]
I fixed this while implementing support for a custom email server, although forgot to mention it in my commit comment. See pull request #19.
