### ISSUE TITLE
Backup Failed no InstanceIDs to process

### ISSUE THREAD

**Issue by cappat** [noahlh/aws-automated-backup-powershell#24]
Trying to get this up and running again.  I had an older version working for quite a while.

I think I have this set up correctly but I keep getting the error
Backup failed; no InstanceIDS to process

Any help?

**Comment by noahlh** [comment]
Not sure I can be a huge help, but I'll try -- when you say you had an older version working - what changed?  Version of this script or on a new machine (or both?)

**Comment by cappat** [comment]
Sorry - I figured it out.
My instances didn't have BACKUP tag = Yes
Once I added those everything started working again!

Instructions are good.  I just had to be more meticulous when I was setting up.

Thanks Again!  Great tool!

**Comment by noahlh** [comment]
Woo hoo!  Great to hear.
