### ISSUE TITLE
Missing Something

### ISSUE THREAD

**Issue by bpatteson** [noahlh/aws-automated-backup-powershell#26]
I followed the documentation but I am missing something here when it comes to this line

$backupTag = "xxxxxxxx" #Make sure the value of this Tag is 'Yes', without the quotes, on the instances you want backed up

In AWS I put tags on the instances that are to be backed up.  The tags I put in are:  Backup - Yes and BackupTag - Yes.  Does the "xxxxxxxx" get left in the script as is above?

I am getting Backup failed: no InstanceIDs to process.

**Comment by LucasSymons** [comment]
Tag's are a key, value pair. This is asking for $backupTag = "xxxxxxxx" to be set as the Key you are using on your instances. 
e.g. 
Tag: Key = BackupEnabled, Value = Yes
$backupTag = "BackupEnabled"
